//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Stok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Musteriler()
        {
            this.Tbl_Satıslar = new HashSet<Tbl_Satıslar>();
        }
    
        public int MsuteriId { get; set; }
       
        [Required (ErrorMessage ="Bu alanı boş bırakamazsınız.")]
        [StringLength(50,ErrorMessage ="En fazla 50 karakterlik isim girin")]
        public string MusteriAdı { get; set; }
        public string MusteriSoyadı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satıslar> Tbl_Satıslar { get; set; }
    }
}
